---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotrod
  namespace: netic-hotrod-app
  labels:
    app.kubernetes.io/name: hotrod
    app.kubernetes.io/instance: hotrod
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hotrod
      app.kubernetes.io/instance: hotrod
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hotrod
        app.kubernetes.io/instance: hotrod
      annotations:
        sidecar.opentelemetry.io/inject: "true"
    spec:
      containers:
        - name: hotrod
          image: jaegertracing/example-hotrod:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 512Mi
