---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotrod
  namespace: netic-hotrod-app
  labels:
    app.kubernetes.io/name: hotrod
    app.kubernetes.io/instance: hotrod
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hotrod
      app.kubernetes.io/instance: hotrod
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hotrod
        app.kubernetes.io/instance: hotrod
      annotations:
        sidecar.opentelemetry.io/inject: "true"
    spec:
      containers:
        - name: hotrod
          image: jaegertracing/example-hotrod:latest
          imagePullPolicy: Always
          args:
            - all
            - -m
            - prometheus
          ports:
            - name: http
              containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsUser: 1000
            runAsNonRoot: true
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 512Mi
