---
apiVersion: v1
kind: Service
metadata:
  name: jytte-service
  namespace: horsezilla-online-team-a-app
  labels:
    app.kubernetes.io/name: hotrod
    app.kubernetes.io/instance: hotrod
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: hotrod
    app.kubernetes.io/instance: hotrod
