---
apiVersion: v1
kind: Namespace
metadata:
  name: netic-ingress-system
  labels:
    name: netic-ingress-system
    netic.dk/monitoring: "true"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour
  namespace: netic-ingress-system
spec:
  chart:
    spec:
      chart: contour
      version: "4.3.5"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: netic-gitops-system
      interval: 5m

  interval: 5m
  releaseName: contour

  values:
    contour:
      extraArgs:  # Disables access log as it generates a lot of log noise
      - --envoy-http-access-log=/dev/null
      - --envoy-https-access-log=/dev/null
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: contour-contour-patch
  namespace: netic-ingress-system
  labels:
    netic.dk/monitoring: "true"
spec:
  jobLabel: "app.kubernetes.io/name"
  selector:
    matchLabels:
      app.kubernetes.io/name: contour
      app.kubernetes.io/instance: contour
      app.kubernetes.io/component: contour
  namespaceSelector:
    matchNames:
      - netic-ingress-system
  endpoints:
    - port: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: contour-envoy-patch
  namespace: netic-ingress-system
  labels:
    netic.dk/monitoring: "true"
spec:
  jobLabel: "app.kubernetes.io/name"
  selector:
    matchLabels:
      app.kubernetes.io/name: contour
      app.kubernetes.io/instance: contour
      app.kubernetes.io/component: envoy
  namespaceSelector:
    matchNames:
      - netic-ingress-system
  endpoints:
    - port: metrics
      path: /stats/prometheus
