---
apiVersion: v1
kind: Namespace
metadata:
  name: netic-security-system
  labels:
    name: netic-security-system
    netic.dk/monitoring: "true"
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: gatekeeper
  namespace: netic-gitops-system
spec:
  url: https://open-policy-agent.github.io/gatekeeper/charts
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: netic-security-system
spec:
  chart:
    spec:
      chart: gatekeeper
      version: "3.3.0"
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
        namespace: netic-gitops-system
      interval: 2m

  releaseName: gatekeeper
  interval: 2m
