---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotrod
  labels:
    app.kubernetes.io/name: hotrod
    app.kubernetes.io/instance: hotrod
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hotrod
      app.kubernetes.io/instance: hotrod
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hotrod
        app.kubernetes.io/instance: hotrod
        netic.dk/network-ingress: contour
    spec:
      containers:
        - name: hotrod
          image: jaegertracing/example-hotrod:latest
          imagePullPolicy: Always
          args:
            - all
            - -m
            - prometheus
          env:
            - name: JAEGER_AGENT_HOST
              value: localhost
            - name: JAEGER_AGENT_PORT
              value: "6831"
          ports:
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 8083
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsUser: 1000
            runAsNonRoot: true
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 512Mi
