---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cert-manager-controller
  namespace: cert-manager
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/component: controller
  policyTypes:
    - Egress
    - Ingress
  ingress:
    - ports:
        - port: 9402
          protocol: TCP
  egress:
    - ports:  # DNS and API server
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
        - port: 443
          protocol: TCP
        - port: 6443
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cert-manager-cainjector
  namespace: cert-manager
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cainjector
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/component: cainjector
  policyTypes:
    - Egress
    - Ingress
  ingress: []
  egress:
    - ports:  # DNS and API server
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
        - port: 443
          protocol: TCP
        - port: 6443
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cert-manager-webhook
  namespace: cert-manager
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: webhook
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/component: webhook
  policyTypes:
    - Egress
    - Ingress
  ingress:
    - ports:
        - port: https
          protocol: TCP
  egress:
    - ports:  # DNS and API server
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
        - port: 443
          protocol: TCP
        - port: 6443
          protocol: TCP
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 2m
  chart:
    spec:
      chart: cert-manager
      version: "1.3.1"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: netic-gitops-system
      interval: 2m
  releaseName: cert-manager
  values:
    global:
      podSecurityPolicy:
        enabled: true
    installCRDs: true
